version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - myproject_network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - myproject_network

networks:
  myproject_network:

